stages:
  - check

lint-frontend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd frontend
    - npm install
    - npm run check-formatting

lint-backend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd backend
    - npm install
    - npm run check-formatting
