stages:
  - check
  - test

variables:
  MARIADB_ROOT_PASSWORD: abcd
  DB_HOST: mariadb
  DB_PASSWORD: abcd

lint-frontend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd frontend
    - npm install
    - npm run check-formatting

lint-backend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd backend
    - npm install
    - npm run check-formatting

test-backend:
  image: node:16
  services:
    - mariadb:10
  tags:
    - hva
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test


test-frontend:
  image: node:16-alpine
  tags:
    - hva
  stage: test
  allow_failure: true
  variables:
    CHROME_BIN: "/usr/bin/chromium-browser --no-sandbox --disable-gpu"
  script:
    - apk add --no-cache chromium
    - cd frontend
    - npm install
    - npm run test-ci
