stages:
  - check
  - test

variables:
  MYSQL_ROOT_PASSWORD: password

lint-frontend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd frontend
    - npm install
    - npm run check-formatting

lint-backend:
  image: node:16
  tags:
    - hva
  stage: check
  script:
    - cd backend
    - npm install
    - npm run check-formatting

test-backend:
  image: node:16
  services:
    - mysql:8-oracle
  tags:
    - hva
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
