@startuml PlantUML Sequence Diagram - GetBoatsOverviewData - Stef Korporaal
autoactivate on

actor Actor

Actor ->> BoatController : getBoatsOverviewData(req, res)

BoatController ->> BoatService : getBoatsOverviewData()

BoatService ->> BoatService : returnAllBoatsNotInMaintenance()

BoatService ->> BoatDao : getBoats()

create BoatModel
BoatDao ->> BoatModel : <<static>>\nfindAll()
return BoatModel[]

loop boats.map
    BoatDao -> BoatDao : model.toBoat()

    create Boat
    BoatDao -> Boat : <<create>>
    return Boat

    return Boat
end

return Boat[]

loop boats.filter
    BoatService -> BoatService: model.toBoat()
    return Boat
end

return Boat[]

loop boats.map
    BoatService ->> BoatService : BoattInstanceToOverviewData()

    BoatService -> Boat: getRequirements()

    return Requirements

    return BoatOverviewData
end

return BoatOverviewData[]

return response

@enduml
