@startuml PlantUML Sequence Diagram - Login - Stef Korporaal
autoactivate on

actor Actor
participant LoginController
participant SessionService
participant UserService
participant UserDao
participant UserModel
participant User
participant Session
participant SessionDao
participant SessionModel

Actor ->> LoginController : login(res, req)

LoginController ->> SessionService : login(email, password)

SessionService ->> UserService : getUserByEmail(email)

UserService ->> UserDao : getUserByEmail(email)

create UserModel
UserDao ->> UserModel : <<static>>\nfindOne()

return UserModel

create User
UserDao -> User : <<static>>\nfromModel()

return User

return User

return User

SessionService ->> User : verifyPassword(password)

return User

create Session
SessionService ->> Session : <<static>>\ncreateSessionForUser(user)

Session -> Session : <<static>>\ngenerateSessionId()

Session --> Session : sessionId

return Session

SessionService ->> SessionDao : saveSession(user)

create SessionModel
SessionDao ->> SessionModel : <<static>>\nsaveSession(session)

return void

return void

return Session

return response


@enduml
