@startuml PlantUML Sequence Diagram - GetBoatsOverviewData - Stef Korporaal
autoactivate on

actor Actor
participant BoatController
participant BoatService
participant BoatDao
participant BoatModel
participant Boat

Actor ->> BoatController : getBoatsOverviewData(req, res)

BoatController ->> BoatService : getBoatsOverviewData()

BoatService ->> BoatService : returnAllBoatsNotInMaintenance()

BoatService ->> BoatDao : getBoats()

BoatDao ->> BoatModel : <<static>>\nfindAll()
return BoatModel[]

loop boats.map
    BoatDao -> BoatDao: model.toBoat()
    return Boat
end

return Boat[]

loop boats.filter
    BoatService -> BoatService: model.toBoat()
    return Boat
end

return Boat[]

loop boats.map
    BoatService ->> BoatService : BoattInstanceToOverviewData()

    BoatService -> Boat: getRequirements()

    return Requirements

    return BoatOverviewData
end

return BoatOverviewData[]

return response

@enduml
